name: CI

on:
  pull_request:

jobs:
  ruby-ci:
    strategy:
      matrix:
        # runs-on: [ubicloud, ubuntu-latest, namespace-profile-default, buildjet-2vcpu-ubuntu-2204]
        # runs-on: [ubuntu-20.04, ubuntu-22.04, ubicloud-standard-2-ubuntu-2004, ubicloud-standard-2-ubuntu-2004, ubicloud-standard-2-ubuntu-2204, ubicloud-standard-2-ubuntu-2204]
        # runs-on: [ubuntu-latest]
        runs-on: [ubuntu-latest]
        # runs-on: [ubuntu-latest, ubicloud-standard-2-ubuntu-2004, ubicloud-standard-2-ubuntu-2204, ubicloud-standard-2-arm-ubuntu-2004, ubicloud-standard-2-arm-ubuntu-2204]
        # runs-on: [ubuntu-22.04, ubicloud-standard-2, ubicloud-standard-4, ubicloud-standard-8, ubicloud-standard-16]
    name: CI ${{matrix.runs-on}}
    runs-on: ${{matrix.runs-on}}
    continue-on-error: true
    env:
      DB_USER: clover
      DB_PASSWORD: nonempty
      DB_NAME: clover_test
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: uname -mr
        run: uname -mr

      # - name: lsb_release -a
      #   run: lsb_release -a

      - name: printenv
        run: printenv
