name: CI

on:
  push:
    branches:
      - build-test
  pull_request:

jobs:
  ruby-ci:
    strategy:
      matrix:
        # runs-on: [ubicloud, ubuntu-latest, namespace-profile-default, buildjet-2vcpu-ubuntu-2204]
        runs-on: [ubuntu-latest, ubicloud-standard-2-ubuntu-2204, ubicloud-standard-2-ubuntu-2004, ubicloud-standard-2-ubuntu-2204-arm]
        # runs-on: [ubuntu-22.04, ubicloud-standard-2, ubicloud-standard-4, ubicloud-standard-8, ubicloud-standard-16]
    name: CI ${{matrix.runs-on}}
    runs-on: ${{matrix.runs-on}}
    continue-on-error: true
    env:
      DB_USER: clover
      DB_PASSWORD: nonempty
      DB_NAME: clover_test

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: uname -mr
        run: uname -mr

      - name: lsb_release -a
        run: lsb_release -a

      - name: printenv
        run: printenv

      - name: sudo fsck -nf
        run: sudo fsck -nf

      - name: ls -lah
        run: ls -lah

      - name: df -Th
        run: df -Th

      - name: ls -lah /home/runner
        run: ls -lah /home/runner

      - name: ls -lah /home/runner/runners || true
        run: ls -lah /home/runner/runners || true

      - name: ls -lah /home/runner/runners/2.312.0 || true
        run: ls -lah /home/runner/runners/2.312.0 || true

      - name: ls -lah /home/runner/actions-runner || true
        run: ls -lah /home/runner/actions-runner || true

      - name: sudo -l
        run: sudo -l

      - name: sudo ls -lah /etc/sudoers.d
        run: sudo ls -lah /etc/sudoers.d

      - name: sudo cat /etc/sudoers.d/runner || true
        run: sudo cat /etc/sudoers.d/runner || true

      - name: docker run -d -v "$(pwd)":/workspace --name alpine alpine tail -f /dev/null
        run: docker run -d -v "$(pwd)":/workspace --name alpine alpine tail -f /dev/null

      - name: docker exec alpine ls -lah
        run: docker exec alpine ls -lah

      - name: docker exec alpine ls -lah /workspace
        run: docker exec alpine ls -lah /workspace

      - name: docker exec alpine touch /workspace/test.txt
        run: docker exec alpine touch /workspace/test.txt

      - name: docker exec alpine ls -lah /workspace
        run: docker exec alpine ls -lah /workspace

      - name: cat /etc/group
        run: cat /etc/group

      - name: groups runner
        run: groups runner

      - name: cat /proc/meminfo
        run: cat /proc/meminfo

      - name: swapon -s
        run: swapon -s

      - name: free -h
        run: free -h

      - name: swapon --all --verbose
        run: swapon --all --verbose

      - name: cat /proc/swaps
        run: cat /proc/swaps
