name: CI

on:
  push:
    branches:
      - build-test
  pull_request:

jobs:
  ruby-ci:
    strategy:
      matrix:
        # runs-on: [ubicloud, ubuntu-latest, namespace-profile-default, buildjet-2vcpu-ubuntu-2204]
        runs-on: [ubuntu-latest, ubuntu-latest, ubuntu-latest]
        # runs-on: [ubuntu-22.04, ubicloud-standard-2, ubicloud-standard-4, ubicloud-standard-8, ubicloud-standard-16]
    name: CI ${{matrix.runs-on}}
    runs-on: ${{matrix.runs-on}}
    continue-on-error: true
    env:
      DB_USER: clover
      DB_PASSWORD: nonempty
      DB_NAME: clover_test

    services:
      postgres:
        image: postgres:15.4
        env:
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
          POSTGRES_DB: ${{ env.DB_NAME }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: nproc
        run: nproc
