name: CI

on:
  push:
    branches:
      - build-test
  pull_request:

jobs:
  ruby-ci:
    strategy:
      matrix:
        # runs-on: [ubicloud, ubuntu-latest, namespace-profile-default, buildjet-2vcpu-ubuntu-2204]
        # runs-on: [ubuntu-20.04, ubuntu-22.04, ubicloud-standard-2-ubuntu-2004, ubicloud-standard-2-ubuntu-2004, ubicloud-standard-2-ubuntu-2204, ubicloud-standard-2-ubuntu-2204]
        # runs-on: [ubuntu-latest]
        runs-on: [self-hosted]
        # runs-on: [ubuntu-latest, ubicloud-standard-2-ubuntu-2004, ubicloud-standard-2-ubuntu-2204, ubicloud-standard-2-arm-ubuntu-2004, ubicloud-standard-2-arm-ubuntu-2204]
        # runs-on: [ubuntu-22.04, ubicloud-standard-2, ubicloud-standard-4, ubicloud-standard-8, ubicloud-standard-16]
    name: CI ${{matrix.runs-on}}
    runs-on: ${{matrix.runs-on}}
    continue-on-error: true
    env:
      DB_USER: clover
      DB_PASSWORD: nonempty
      DB_NAME: clover_test
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: uname -mr
        run: uname -mr

      # - name: lsb_release -a
      #   run: lsb_release -a

      - name: printenv
        run: printenv

      # - run: export ACTIONS_CACHE_URL=https://6228-212-154-66-44.ngrok-free.app

      - name: echo $ACTIONS_CACHE_URL
        run: echo $ACTIONS_CACHE_URL

      - name: echo $ACTIONS_RUNTIME_TOKEN
        run: echo $ACTIONS_RUNTIME_TOKEN

      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: demo
          key: cache-2

      - name: echo $ACTIONS_CACHE_URL
        run: echo $ACTIONS_CACHE_URL

      - name: echo $ACTIONS_RUNTIME_TOKEN
        run: echo $ACTIONS_RUNTIME_TOKEN

      - name: echo $PATH
        run: echo $PATH

      # - name: cat /home/runner/actions-runner/.env
      #   continue-on-error: true
      #   run: cat /home/runner/actions-runner/.env

      # - name: ls -lah /home/runner
      #   run: ls -lah /home/runner
