name: E2E CI

on:
  workflow_dispatch:
    inputs:
      enable_vm:
        description: Enable VM tests
        default: true
        type: boolean
      enable_github_2204:
        description: Enable GitHub Ubuntu 22.04 test
        default: false
        type: boolean
      enable_github_2004:
        description: Enable GitHub Ubuntu 20.04 test
        default: false
        type: boolean

  # schedule:
  #   - cron:  '0 */1 * * *'

jobs:
  run-ci:
    runs-on: ubuntu-latest
    environment: E2E-CI
    timeout-minutes: 45
    concurrency: e2e_environment

    env:
      DB_USER: clover
      DB_PASSWORD: nonempty
      DB_NAME: clover_test

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .tool-versions
        bundler-cache: true

    - name: run ci script
      run: |
        test_cases=""
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          if [[ "${{ inputs.enable_vm }}" == "true" ]]; then
             test_cases="${test_cases}vm,"
          fi
          if [[ "${{ inputs.enable_github_2204 }}" == "true" ]]; then
             test_cases="${test_cases}github_runner_ubuntu_2204,"
          fi
          if [[ "${{ inputs.enable_github_2004 }}" == "true" ]]; then
             test_cases="${test_cases}github_runner_ubuntu_2004,"
          fi
        else
           test_cases="vm"
        fi

        ./bin/ci --test-cases=$test_cases
