name: E2E CI

on:
  workflow_dispatch:
    inputs:
      test_cases:
        description: 'Comma-separated list of test cases (vm)'
        required: true
        default: 'vm'
        type: string

  # schedule:
  #   - cron:  '0 */1 * * *'

jobs:
  run-ci:
    runs-on: ubuntu-latest
    environment: E2E-CI
    timeout-minutes: 45
    concurrency: e2e_environment

    env:
      DB_USER: clover
      DB_PASSWORD: nonempty
      DB_NAME: clover_test

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .tool-versions
        bundler-cache: true

    - name: run ci script
      run: |
        ./bin/ci --test-cases=${{ github.event_name != 'workflow_dispatch' && 'vm' || inputs.test_cases }}"
